baseURL = "https://backaboulder.se/"
languageCode = "en-us"
disableKinds = ["section", "taxonomy", "term", "RSS"]
DefaultContentLanguage = "sv"
enableRobotsTXT = true

[languages]
  [languages.sv]
    languageName = "Svenska"
    title = "Bagarn Bengtsson"
    weight = 1
    contentDir = "content/sv"
    [languages.sv.params]
      LanguageCode = "sv"
      UseString = "På svenska"
  [languages.en]
    languageName = "English"
    title = "Bengtsson the baker"
    weight = 2
    contentDir = "content/en"
    [languages.en.params]
      LanguageCode = "en"
      UseString = "In English"
